// DON'T CHANGE THIS FILE MANUALLY. IT IS GENERATED AUTOMATICALLY.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3a6izOWDvpmVYLMv_VR9M_WYdN4LaGWc',
    appId: '1:1029240583657:web:9d50f519bc885473504778',
    messagingSenderId: '1029240583657',
    projectId: 'pops-226ca',
    authDomain: 'pops-226ca.firebaseapp.com',
    databaseURL: 'https://pops-226ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pops-226ca.appspot.com',
    measurementId: 'G-02PN5QHG7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23Cb8onFML0u35q1QpzSB4Ye_-d-IKPg',
    appId: '1:1029240583657:android:e063c8bdc42ca7c1504778',
    messagingSenderId: '1029240583657',
    projectId: 'pops-226ca',
    databaseURL: 'https://pops-226ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pops-226ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD38hdyELn3Pt2_VIJMGfEn8sGzXPlYUJA',
    appId: '1:1029240583657:ios:5392d5fee797138b504778',
    messagingSenderId: '1029240583657',
    projectId: 'pops-226ca',
    databaseURL: 'https://pops-226ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pops-226ca.appspot.com',
    iosClientId: '1029240583657-sp3afpstbbeambe30nj5iebt9uihph36.apps.googleusercontent.com',
    iosBundleId: 'com.example.pops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD38hdyELn3Pt2_VIJMGfEn8sGzXPlYUJA',
    appId: '1:1029240583657:ios:5392d5fee797138b504778',
    messagingSenderId: '1029240583657',
    projectId: 'pops-226ca',
    databaseURL: 'https://pops-226ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pops-226ca.appspot.com',
    iosClientId: '1029240583657-sp3afpstbbeambe30nj5iebt9uihph36.apps.googleusercontent.com',
    iosBundleId: 'com.example.pops',
  );
}
